[2023-01-23T14:52:25.157+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_extraction_and_loading_5.load_data scheduled__2022-02-06T00:00:00+00:00 [queued]>
[2023-01-23T14:52:25.164+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_extraction_and_loading_5.load_data scheduled__2022-02-06T00:00:00+00:00 [queued]>
[2023-01-23T14:52:25.164+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T14:52:25.165+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-23T14:52:25.166+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T14:52:25.174+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_data> on 2022-02-06 00:00:00+00:00
[2023-01-23T14:52:25.180+0000] {standard_task_runner.py:55} INFO - Started process 2298 to run task
[2023-01-23T14:52:25.182+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_and_loading_5', 'load_data', 'scheduled__2022-02-06T00:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpo2xj18df']
[2023-01-23T14:52:25.184+0000] {standard_task_runner.py:83} INFO - Job 124: Subtask load_data
[2023-01-23T14:52:25.195+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-01-23T14:52:25.210+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-01-23T14:52:25.234+0000] {task_command.py:388} INFO - Running <TaskInstance: data_extraction_and_loading_5.load_data scheduled__2022-02-06T00:00:00+00:00 [running]> on host 1b696c32fad4
[2023-01-23T14:52:25.283+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=abdessamad
AIRFLOW_CTX_DAG_ID=data_extraction_and_loading_5
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-06T00:00:00+00:00
[2023-01-23T14:52:25.292+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 27, in load_data
    pickled_data_extractor, data = kwargs['ti'].xcom_pull(key=None, task_ids='first_task')
TypeError: cannot unpack non-iterable NoneType object
[2023-01-23T14:52:25.301+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_and_loading_5, task_id=load_data, execution_date=20220206T000000, start_date=20230123T145225, end_date=20230123T145225
[2023-01-23T14:52:25.311+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 124 for task load_data (cannot unpack non-iterable NoneType object; 2298)
[2023-01-23T14:52:25.355+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-23T14:52:25.372+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
