[2023-01-23T14:51:06.156+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_extraction_and_loading_5.load_data scheduled__2022-01-23T00:00:00+00:00 [queued]>
[2023-01-23T14:51:06.167+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_extraction_and_loading_5.load_data scheduled__2022-01-23T00:00:00+00:00 [queued]>
[2023-01-23T14:51:06.168+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T14:51:06.169+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-23T14:51:06.170+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T14:51:06.179+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_data> on 2022-01-23 00:00:00+00:00
[2023-01-23T14:51:06.184+0000] {standard_task_runner.py:55} INFO - Started process 2238 to run task
[2023-01-23T14:51:06.188+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_and_loading_5', 'load_data', 'scheduled__2022-01-23T00:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmplb1bdptn']
[2023-01-23T14:51:06.191+0000] {standard_task_runner.py:83} INFO - Job 119: Subtask load_data
[2023-01-23T14:51:06.203+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-01-23T14:51:06.223+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-01-23T14:51:06.247+0000] {task_command.py:388} INFO - Running <TaskInstance: data_extraction_and_loading_5.load_data scheduled__2022-01-23T00:00:00+00:00 [running]> on host 1b696c32fad4
[2023-01-23T14:51:06.291+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=abdessamad
AIRFLOW_CTX_DAG_ID=data_extraction_and_loading_5
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2022-01-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-23T00:00:00+00:00
[2023-01-23T14:51:06.300+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 27, in load_data
    pickled_data_extractor, data = kwargs['ti'].xcom_pull(key=None, task_ids='first_task')
TypeError: cannot unpack non-iterable NoneType object
[2023-01-23T14:51:06.308+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_and_loading_5, task_id=load_data, execution_date=20220123T000000, start_date=20230123T145106, end_date=20230123T145106
[2023-01-23T14:51:06.316+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 119 for task load_data (cannot unpack non-iterable NoneType object; 2238)
[2023-01-23T14:51:06.361+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-23T14:51:06.374+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
