[2023-01-29T15:44:55.314+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_pipeline_1.extract_data manual__2023-01-29T15:44:47.106705+00:00 [queued]>
[2023-01-29T15:44:55.322+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_pipeline_1.extract_data manual__2023-01-29T15:44:47.106705+00:00 [queued]>
[2023-01-29T15:44:55.323+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T15:44:55.324+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-01-29T15:44:55.325+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T15:44:55.334+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): extract_data> on 2023-01-29 15:44:47.106705+00:00
[2023-01-29T15:44:55.347+0000] {standard_task_runner.py:55} INFO - Started process 1250 to run task
[2023-01-29T15:44:55.358+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_1', 'extract_data', 'manual__2023-01-29T15:44:47.106705+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp14ynysbr']
[2023-01-29T15:44:55.364+0000] {standard_task_runner.py:83} INFO - Job 96: Subtask extract_data
[2023-01-29T15:44:55.395+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-01-29T15:44:55.457+0000] {task_command.py:388} INFO - Running <TaskInstance: data_pipeline_1.extract_data manual__2023-01-29T15:44:47.106705+00:00 [running]> on host e0a1e7e3563d
[2023-01-29T15:44:55.532+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=abdessamad
AIRFLOW_CTX_DAG_ID=data_pipeline_1
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-29T15:44:47.106705+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-29T15:44:47.106705+00:00
[2023-01-29T15:45:24.990+0000] {etl.py:120} ERROR - Error
[2023-01-29T15:45:25.068+0000] {etl.py:120} ERROR - Error
[2023-01-29T15:45:25.204+0000] {etl.py:120} ERROR - Error
[2023-01-29T15:45:25.362+0000] {etl.py:120} ERROR - Error
[2023-01-29T15:45:55.541+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6947835f7e228ea9e8d86, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:46:25.680+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6947835f7e228ea9e8d86, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:46:55.899+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6947835f7e228ea9e8d86, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:47:26.341+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6947835f7e228ea9e8d86, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:47:56.756+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6947835f7e228ea9e8d86, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:48:26.884+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6947835f7e228ea9e8d86, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:48:57.088+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6947835f7e228ea9e8d86, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:49:27.209+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6947835f7e228ea9e8d86, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:49:57.413+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6947835f7e228ea9e8d86, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:50:27.819+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6947835f7e228ea9e8d86, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:50:41.485+0000] {local_task_job.py:112} ERROR - Received SIGTERM. Terminating subprocesses
[2023-01-29T15:50:42.536+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 1250. PIDs of all processes in the group: [1250]
[2023-01-29T15:50:42.550+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 1250
[2023-01-29T15:50:42.558+0000] {taskinstance.py:1479} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-01-29T15:50:42.601+0000] {logging_mixin.py:137} INFO - Task received SIGTERM signal
[2023-01-29T15:50:43.872+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-29T15:50:44.097+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=data_pipeline_1, task_id=extract_data, execution_date=20230129T154447, start_date=20230129T154455, end_date=20230129T155044
[2023-01-29T15:50:44.693+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1250, status='terminated', exitcode=0, started='15:44:55') (1250) terminated with exit code 0
[2023-01-29T15:50:44.720+0000] {local_task_job.py:208} INFO - Task exited with return code 143
[2023-01-29T15:50:44.901+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
