[2023-01-23T15:31:33.691+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_extraction_and_loading_10.load_data manual__2023-01-23T15:31:31.832984+00:00 [queued]>
[2023-01-23T15:31:33.699+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_extraction_and_loading_10.load_data manual__2023-01-23T15:31:31.832984+00:00 [queued]>
[2023-01-23T15:31:33.699+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T15:31:33.700+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-01-23T15:31:33.701+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-23T15:31:33.709+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_data> on 2023-01-23 15:31:31.832984+00:00
[2023-01-23T15:31:33.714+0000] {standard_task_runner.py:55} INFO - Started process 3544 to run task
[2023-01-23T15:31:33.717+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_extraction_and_loading_10', 'load_data', 'manual__2023-01-23T15:31:31.832984+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp8vi1iegj']
[2023-01-23T15:31:33.719+0000] {standard_task_runner.py:83} INFO - Job 136: Subtask load_data
[2023-01-23T15:31:33.731+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-01-23T15:31:33.768+0000] {task_command.py:388} INFO - Running <TaskInstance: data_extraction_and_loading_10.load_data manual__2023-01-23T15:31:31.832984+00:00 [running]> on host 1b696c32fad4
[2023-01-23T15:31:33.826+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=abdessamad
AIRFLOW_CTX_DAG_ID=data_extraction_and_loading_10
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T15:31:31.832984+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-23T15:31:31.832984+00:00
[2023-01-23T15:31:33.834+0000] {logging_mixin.py:137} INFO - None
[2023-01-23T15:31:33.846+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 34, in load_data
    data_extractor = pickle.loads(pickled_data_extractor)
TypeError: a bytes-like object is required, not 'NoneType'
[2023-01-23T15:31:33.858+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=data_extraction_and_loading_10, task_id=load_data, execution_date=20230123T153131, start_date=20230123T153133, end_date=20230123T153133
[2023-01-23T15:31:33.868+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 136 for task load_data (a bytes-like object is required, not 'NoneType'; 3544)
[2023-01-23T15:31:33.890+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-01-23T15:31:33.903+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
