[2023-01-29T15:39:09.420+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_pipeline.extract_data manual__2023-01-29T15:39:03.281905+00:00 [queued]>
[2023-01-29T15:39:09.430+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: data_pipeline.extract_data manual__2023-01-29T15:39:03.281905+00:00 [queued]>
[2023-01-29T15:39:09.431+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T15:39:09.432+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 3
[2023-01-29T15:39:09.432+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-01-29T15:39:09.442+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): extract_data> on 2023-01-29 15:39:03.281905+00:00
[2023-01-29T15:39:09.481+0000] {standard_task_runner.py:55} INFO - Started process 1101 to run task
[2023-01-29T15:39:09.486+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'extract_data', 'manual__2023-01-29T15:39:03.281905+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpiz_bsskt']
[2023-01-29T15:39:09.490+0000] {standard_task_runner.py:83} INFO - Job 95: Subtask extract_data
[2023-01-29T15:39:09.514+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-01-29T15:39:09.580+0000] {task_command.py:388} INFO - Running <TaskInstance: data_pipeline.extract_data manual__2023-01-29T15:39:03.281905+00:00 [running]> on host e0a1e7e3563d
[2023-01-29T15:39:09.648+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=abdessamad
AIRFLOW_CTX_DAG_ID=data_pipeline
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-01-29T15:39:03.281905+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-29T15:39:03.281905+00:00
[2023-01-29T15:39:35.089+0000] {etl.py:120} ERROR - Error
[2023-01-29T15:39:35.148+0000] {etl.py:120} ERROR - Error
[2023-01-29T15:39:35.217+0000] {etl.py:120} ERROR - Error
[2023-01-29T15:39:35.280+0000] {etl.py:120} ERROR - Error
[2023-01-29T15:39:35.359+0000] {etl.py:120} ERROR - Error
[2023-01-29T15:39:35.436+0000] {etl.py:120} ERROR - Error
[2023-01-29T15:40:05.629+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6931ed8c606a770818099, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:40:36.022+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6931ed8c606a770818099, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:41:06.417+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6931ed8c606a770818099, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:41:36.448+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6931ed8c606a770818099, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:42:06.476+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6931ed8c606a770818099, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:42:36.797+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6931ed8c606a770818099, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:43:07.284+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6931ed8c606a770818099, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:43:37.751+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6931ed8c606a770818099, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:44:08.237+0000] {logging_mixin.py:137} INFO - mongo_db:27017: [Errno -2] Name or service not known, Timeout: 30s, Topology Description: <TopologyDescription id: 63d6931ed8c606a770818099, topology_type: Unknown, servers: [<ServerDescription ('mongo_db', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo_db:27017: [Errno -2] Name or service not known')>]>
[2023-01-29T15:44:08.494+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-29T15:44:08.512+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=extract_data, execution_date=20230129T153903, start_date=20230129T153909, end_date=20230129T154408
[2023-01-29T15:44:08.597+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-01-29T15:44:08.649+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
